<a href="https://colab.research.google.com/github/HARSHA0232/EDA-DIGTAL-ASSIGNMENT---1-/blob/main/Module_2_Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 2: Data Transformation

## Student Details
**Name**: BAJJURI HARSHA VARDHAN
**Registration Number**: 21BDS0232
**DIGITAL ASSIGNMENT - 1**

## Overview
This module covers data transformation techniques applied to the dataset, including handling missing values, discretization, deduplication, and outlier detection. The traditional method of Maximum Likelihood Estimation (MLE) will be used to estimate missing values.

## Step 1: Load the Dataset
Load the dataset directly from the GitHub repository.

In [1]:

# Importing the necessary libraries
import pandas as pd

# Load the dataset from GitHub link
url = 'https://github.com/HARSHA0232/EDA-DIGTAL-ASSIGNMENT---1-/blob/main/student-mat.csv?raw=true'
data = pd.read_csv(url)

# Display the first few rows of the dataset
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

## Step 2: Data Deduplication
Check and remove duplicate entries to ensure data quality.

In [2]:

# Check for duplicate rows
duplicates = data.duplicated()
print(f"Number of duplicate rows: {duplicates.sum()}")

# Remove duplicates if present
data = data.drop_duplicates()
print(f"Dataset shape after removing duplicates: {data.shape}")

Number of duplicate rows: 0
Dataset shape after removing duplicates: (395, 33)

## Step 3: Handling Missing Data
Identify and handle missing values in the dataset using traditional methods.

In [5]:


# Check for missing values in each column
missing_values = data.isnull().sum()
print("Missing values in each column:")
print(missing_values)

# Handling missing values in 'G1' column with the mean (example column, replace with the actual column as needed)
if 'G1' in data.columns:
    data['G1'].fillna(data['G1'].mean(), inplace=True)

# Verify that there are no more missing values
print("Missing values after handling:")
print(data.isnull().sum())

Missing values in each column:
school        0
sex           2
age           0
address       1
famsize       1
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     2
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64
Missing values after handling:
school        0
sex           2
age           0
address       1
famsize       1
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     2
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

## Step 4: Handling Missing Data with Maximum Likelihood Estimation (MLE)
Using MLE to estimate missing values in the 'prestige' column based on other features.

In [6]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Create a new dataset with missing values for illustration
data_mle = data.copy()

# Introduce missing values in a specific column (e.g., 'G1') for demonstration purposes
data_mle.loc[0:5, 'G1'] = np.nan

# Prepare the data for MLE - exclude rows where 'G1' is missing for training
train_data = data_mle.dropna(subset=['G1'])
predict_data = data_mle[data_mle['G1'].isnull()]

# Define the features (excluding 'G1') and target ('G1')
# Replace 'age', 'Medu', and 'Fedu' with relevant columns from your dataset
X_train = train_data[['age', 'Medu', 'Fedu']]
y_train = train_data['G1']
X_predict = predict_data[['age', 'Medu', 'Fedu']]

# Train a simple linear regression model as an MLE estimator
mle_model = LinearRegression()
mle_model.fit(X_train, y_train)

# Predict missing 'G1' values using MLE
predicted_values = mle_model.predict(X_predict)
data_mle.loc[data_mle['G1'].isnull(), 'G1'] = predicted_values

# Display the updated dataset with estimated 'G1' values
print(data_mle.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences         G1  G2  G3
0      4        3      4     1     1      3        6  11.845701   6   6
1      5        3      3     1     1      3        4   9.751633   5   6
2      4        3      2     2     3      3       10   9.852293   8  10
3      3        2      2     1     1      5        2  11.324583  14  15
4      4        3      2     1     2      5        4  11.231561  10  10

[5 rows x 33 columns]

## Step 5: Data Discretization
Discretize continuous variables like 'articles' into categorical bins.

In [8]:

import pandas as pd



# Define bins for discretizing 'G1' column
bins = [0, 5, 10, 15, 20]
labels = ['0-5', '6-10', '11-15', '16-20']
data['G1_binned'] = pd.cut(data['G1'], bins=bins, labels=labels)

# Display the updated dataframe with binned categories
print(data[['G1', 'G1_binned']].head())

   G1 G1_binned
0   5       0-5
1   5       0-5
2   7      6-10
3  15     11-15
4   6      6-10

## Step 6: Outlier Detection
Detect and handle outliers in numerical data using the Interquartile Range (IQR) method.

In [9]:



# Outlier detection using Interquartile Range (IQR) for 'G1' column
Q1 = data['G1'].quantile(0.25)
Q3 = data['G1'].quantile(0.75)
IQR = Q3 - Q1

# Defining outlier thresholds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Detecting outliers
outliers = data[(data['G1'] < lower_bound) | (data['G1'] > upper_bound)]
print(f"Number of outliers detected: {len(outliers)}")

# Optionally remove outliers (uncomment the line below to remove them)
# data = data[(data['G1'] >= lower_bound) & (data['G1'] <= upper_bound)]

print(f"Dataset shape after outlier handling: {data.shape}")

Number of outliers detected: 0
Dataset shape after outlier handling: (395, 34)

## Summary
This notebook demonstrates essential data transformation techniques on the `student-mat.csv` dataset. It includes deduplication to eliminate duplicate entries, ensuring data integrity. Missing values in the `'G1'` column are addressed using Maximum Likelihood Estimation (MLE) with linear regression. The notebook also applies discretization to categorize `'G1'` grades and performs outlier detection using the Interquartile Range (IQR) method. These transformations prepare the dataset for reliable insights in further analysis.